spring:
  datasource:
    url: jdbc:mysql://personas-microservice.cd4ic2syiht1.us-east-2.rds.amazonaws.com:3306/persona_microservice?useSSL=true&requireSSL=true
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:Exa4mpleDatab4se}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000 # 10 minutos
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true

springdoc:
  swagger-ui:
    use-root-path: true                 # sirve /swagger-ui/** correctamente detr√°s de proxy
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs